os:
  - Visual Studio 2015

platform:
  - x64

install:
  - ps: Install-Product node 4.4.4
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test
  - scripts\package.bat

# Environment variable needs to change
environment:
  REDIS_HOST: 54.93.183.16
  REDIS_PORT: 6379

artifacts:
  - path: build\*\*.zip

deploy:
  provider: S3
  access_key_id:
    secure: cq7lgQP04314hwXwM2l0yiUKRcOkwHeKkDHFULrThxE=
  secret_access_key:
    secure: AMUWZVZ4o7lS6f5ogqxTTCqDUR/TYEmPaVXzb7yRRyFUTF/zQFnZHYk1G/j7ie8/
  bucket: ds-server-artifacts
  folder: $(APPVEYOR_REPO_NAME)

build: off